version: "3.8"
services: 
  api: 
    build: ./api/
    container_name: api
    ports:
      - "4000:4000"
    command: npm start
    environment:
      MONGO_URI: mongodb://root:root@db:27017
      JWT_SECRET: ecommerce
    volumes: 
      - "./api/:/app"
      - "/app/node_modules"
      
  db: 
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - db-data:/data/db

volumes: 
  db-data: {}
